// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snhzgndpgnbhbhdkzapv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuaHpnbmRwZ25iaGJoZGt6YXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mjk4MTQsImV4cCI6MjA2NjUwNTgxNH0.GeK1qYgPNDKB7gxFytxaIIJE2rOvWqbG2UQeOuhxLk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);